routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Repositories\Interfaces\TodoRepositoryInterface;
use App\Model\Todo;

Route::get('/', function () {
    return view('welcome');
});

/*
 * See why i use except below
 *
*/
Route::resource('todo', 'TodoController')->except('show', 'edit');
Route::get('todo/create/{date}', 'TodoController@create')->name('todo.createByDate');

/*
 * Note NOT BEST PRACTICE
 * Just to show that you can do like this
 *
*/
Route::get('todo/{date}', function($date, TodoRepositoryInterface $todoRepo) {
    $todos = $todoRepo->getAllByDate($date);
    if (!$todos) {
        abort(404);
    }
    return view('todo.list', compact('todos', 'date'));
})->name('todo.showByDate');

Route::get('todo/{id}/edit', function($id, TodoRepositoryInterface $todoRepo) {
    $todo = $todoRepo->getById($id);
    if (!$todo) {
        abort(404);
    }
    return view('todo.edit', compact('todo'));
})->name('todo.edit');

Route::delete('todo/{date}/delete', function($date, TodoRepositoryInterface $todoRepo) {
    $todos = $todoRepo->getAllByDate($date);
    if (!$todos) {
        abort(404);
    }
    $todoRepo->deleteByDate($date);
    return redirect()->route('todo.index')
        ->with('success', 'Todo Deleted Successfully');
})->name('todo.destroyByDate');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TodoRequest;
use App\Repositories\Interfaces\TodoRepositoryInterface;
use Illuminate\Http\Request;

class TodoController extends Controller
{

    private $todoRepo;

    public function __construct(TodoRepositoryInterface $todoRepo)
    {
        $this->todoRepo = $todoRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $args = [
            'todos' => $this->todoRepo->getAllGroupByDate()
        ];
        return view('todo.index', $args);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($date = '')
    {
        $todo = $this->todoRepo;
        return view('todo.create', compact('todo', 'date'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\TodoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TodoRequest $request)
    {
        $this->todoRepo->create($request->validated());
        return redirect()->route('todo.showByDate', $request->do_at)
            ->with('success', 'Todo Created Successfully');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\TodoRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, TodoRequest $request)
    {
        $todo = $this->todoRepo->getById($id);
        $date = $todo->do_at;
        $this->todoRepo->update($id, $request->validated());
        return redirect()->route('todo.showByDate', $date)
            ->with('success', 'Todo Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todo = $this->validateId($id);
        $date = $todo->do_at;
        $this->todoRepo->delete($id);
        return redirect()->route('todo.showByDate', $date)
            ->with('success', 'Todo Deleted Successfully');
    }

    /**
     * Private method to validate id
     *
     * @param  Integer  $id
     * @return \Illuminate\Http\Response
     */
    private function validateId($id)
    {
        $todo = $this->todoRepo->getById($id);
        if (!$todo) {
            abort(404);
        }
        return $todo;
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/messages.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/todo/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Create Todo</h2>
                        <div class="ml-auto">
                            <a href="{{ route('todo.index') }}" class="btn btn-outline-secondary">Back</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('todo.store') }}" method="post">
                        @csrf
                        @php
                        @endphp
                        <div class="form-group row">
                            <label for="todo-do_at" class="col-md-5">Tanggal</label>
                            <div class="col-md-7 input-group">
                                @if (!empty($date))
                                <input type="hidden" name="do_at" value="{{ $date }}">
                                <input type="text" id="todo-do_at" value="{{ $date }}" class="form-control" disabled>
                                @else
                                <input type="date" name="do_at" id="todo-do_at" value="{{ old('do_at') }}" class="form-control {{ $errors->has('do_at') ? 'is-invalid': '' }}">
                                @endif
                                @if ($errors->has('do_at'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('do_at') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="todo-task" class="col-md-5">Task</label>
                            <div class="col-md-7 input-group">
                                <input type="text" name="task" id="todo-task" value="{{ old('task') }}" class="form-control {{ $errors->has('task') ? 'is-invalid': '' }}">
                                @if ($errors->has('task'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('task') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="todo-note" class="col-md-5">Note</label>
                            <div class="col-md-7 input-group">
                                <textarea name="note" id="todo-note" class="form-control {{ $errors->has('note') ? 'is-invalid': '' }}">{{ old('note') }}</textarea>
                                @if ($errors->has('note'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('note') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-primary btn-lg">Create Todo</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/todo/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Update Todo</h2>
                        <div class="ml-auto">
                            <a href="{{ route('todo.showByDate', $todo->do_at) }}" class="btn btn-outline-secondary">Back</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('todo.update', $todo->id) }}" method="post">
                        {{ method_field('PUT') }}
                        @csrf
                        <div class="form-group row">
                            <label for="todo-do_at" class="col-md-5">Tanggal</label>
                            <div class="col-md-7 input-group">
                                <input type="hidden" name="id" value="{{ $todo->id }}">
                                <input type="text" id="todo-do_at" value="{{ $todo->do_at }}" class="form-control" disabled>
                                @if ($errors->has('do_at'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('do_at') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="todo-task" class="col-md-5">Task</label>
                            <div class="col-md-7 input-group">
                                <input type="text" name="task" id="todo-task" value="{{ $todo->task }}" class="form-control {{ $errors->has('task') ? 'is-invalid': '' }}">
                                @if ($errors->has('task'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('task') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="todo-note" class="col-md-5">Note</label>
                            <div class="col-md-7 input-group">
                                <textarea name="note" id="todo-note" class="form-control {{ $errors->has('note') ? 'is-invalid': '' }}">{{ $todo->note }}</textarea>
                                @if ($errors->has('note'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('note') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="todo-status" class="col-md-5">Status</label>
                            <div class="col-md-7 input-group">
                                <select name="status" id="todo-status" class="form-control {{ $errors->has('status') ? 'is-invalid': '' }}">
                                @foreach (config('task.status') as $key => $status)
                                    <option value="{{ $key }}" {{ ($key === $todo->status) ? 'selected' : '' }}>{{ $status['title'] }}</option>
                                @endforeach
                                </select>
                                @if ($errors->has('status'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-primary btn-lg">Update Todo</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/todo/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>All Todo</h2>
                        <div class="ml-auto">
                            <a href="{{ route('todo.create') }}" class="btn btn-outline-secondary">Create Todo</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @include ('layouts.messages')
                    <table class="table table-striped">
                        <tr>
                            <th>#</th>
                            <th>Date</th>
                            <th>Total To Do</th>
                            <th>Action</th>
                        </tr>
@if (sizeof($todos) === 0)
                        <tr>
                            <td colspan="4">
                                No Data, Create One
                            </td>
                        </tr>
@endif
@foreach ($todos as $key => $todo)
                        <tr>
                            <td>{{ ++$key }}</td>
                            <td>{{ $todo->do_at }}</td>
                            <td>{{ $todo->total }}</td>
                            <td>
                                <a href="{{ route('todo.showByDate', $todo->do_at) }}" class="btn btn-sm btn-outline-primary float-left">View</a>
                                <form class="float-left ml-1" method="post" action="{{ route('todo.destroyByDate', $todo->do_at) }}">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are You Sure ?')">Delete</button>
                                </form>
                            </td>
                        </tr>
@endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/todo/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>All Todo {{ $date }}</h2>
                        <div class="ml-auto">
                            <a href="{{ route('todo.index') }}" class="btn btn-outline-secondary">Back</a>
                            <a href="{{ route('todo.createByDate', $date) }}" class="btn btn-outline-secondary">Create Todo</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
@include ('layouts.messages')
                    <table class="table table-striped">
                        <tr>
                            <th>#</th>
                            <th>Task</th>
                            <th>Note</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
@if (sizeof($todos) === 0)
                        <tr>
                            <td colspan="4">
                                No Data, Create One
                            </td>
                        </tr>
@endif
@foreach ($todos as $key => $todo)
                        <tr>
                            <td>{{ ++$key }}</td>
                            <td>{{ $todo->task }}</td>
                            <td>{{ $todo->note }}</td>
                            <td>
                                <span class="badge badge-{{ config('task.status.'.$todo->status.'.color') }} p-1">
                                    {{ config('task.status.'.$todo->status.'.title') }}
                                </span>
                            </td>
                            <td>
                                <a href="{{ route('todo.edit', $todo->id) }}" class="btn btn-sm btn-outline-primary float-left">Edit</a>
                                <form class="float-left ml-1" method="post" action="{{ route('todo.destroy', $todo->id) }}">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are You Sure ?')">Delete</button>
                                </form>
                            </td>
                        </tr>
@endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/todo/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h1>Berat Tanggal {{ $weight->tanggal }}</h1>
                        <div class="ml-auto">
                            <a href="{{ route('weights.index') }}" class="btn btn-outline-secondary">Kembali</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <th>Tanggal</th>
                            <th>{{ $weight->tanggal }}</th>
                        </tr>
                        <tr>
                            <td>Max</td>
                            <td>{{ number_format($weight->max) }}</td>
                        </tr>
                        <tr>
                            <td>Min</td>
                            <td>{{ number_format($weight->min) }}</td>
                        </tr>
                        <tr>
                            <td>Perbedaan</td>
                            <td>{{ (number_format($weight->max - $weight->min)) }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection